config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :articles

  root :to => "articles#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    if (user.role == "manager" || user.role == "administrator")
      can :manage, :all
    else
      can :read, Article
      # this is where I want to say: can :manage if part of collaboration for article 
    end
  end

    
    # Define abilities for the passed in user here. For example:
    #
       
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :photo,
          :url => "/image/:basename.:extension",  
          :path => ":rails_root/public/image/:basename.:extension" 

    validates_attachment_presence :photo  
    validates_attachment_size :photo, :less_than => 2.megabytes
    validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
 
    def role?(r)
    	role.include? r.to_s
    end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
 
    def authenticate_active_admin_user!
        authenticate_user!
        unless current_user.role?(:administrator)
            flash[:alert] = "You are not authorized to access this resource!"
            redirect_to root_path
        end
    end

     # Catch all CanCan errors and alert the user of the exception
    rescue_from CanCan::AccessDenied do | exception |
      redirect_to root_url, alert: exception.message
    end

end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base

	load_and_authorize_resource

  private

    def article_params
      params.require(:article).permit(:title, :body, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, html: {class: 'form-horizontal', multipart: 'true'}) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :body, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :body, :size => "5x6", class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :image, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.file_field :photo, class: 'form-control' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article, class: 'btn btn-primary btn-ms' %> 
<%= link_to "Back", articles_path, class: 'btn btn-default' %>

app/views/articles/index.html.erb
<style type="text/css">

.img {
  float:left;
  margin-right: 10px;
}  
</style>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View list', articles_path %></li>
  <li><%= link_to 'New Article', new_article_path %></li>
</ul>


<h2>Listing Articles</h2>


    <% @articles.each do |article| %>
     
        <h4><%= article.title %></h4>
        <p class="img">
          <%= image_tag(article.photo.url, :width => 300, class: "img-rounded img-responsive") %>
        </p>
        <p class="art-body">  
          <%= article.body %>
        </p>

        <%= link_to 'Show', article, class: 'btn btn-primary btn-xs' %><br><br>

      
    <% end %><br><br>

<% if can? :update, @article %>
    <%= link_to new_article_path, class: 'btn btn-success nounderline' do %>
	  <i class="glyphicon glyphicon-plus"></i> New Article
	<% end %>
<% end %>

app/views/articles/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View list', articles_path %></li>
  <li class="active"><%= link_to 'New article', new_article_path %></li>
</ul>

<h1>New Article</h1>

<%= render 'form' %>

<%= link_to "Back", articles_path, class: 'btn btn-default' %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <b><%= @article.title %></b>
</p>

<p>
  <%= image_tag(@article.photo.url, :width => 300, :height => 175, class: "img-rounded img-responsive") %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <% if can? :update, @article %>
    <%= link_to "Edit", edit_article_path(@article), class: 'btn btn-info btn-ms' %> 
  <% end %>
  <% if can? :destroy, @article %>
    <%= link_to "Destroy", @article, :method => :delete, :confirm => "Are you sure?", class: 'btn btn-danger btn-ms' %> 
  <% end %>
  <%= link_to "Back", articles_path, class: 'btn btn-default' %>
</p>

app/views/layouts/_footer.html.erb
<style type="text/css">

footer{
	background-color:#BEF6A9;
	height:90px;
	text-align:center;
	padding-top:20px;
	width: 100%;
	position: relative;
	bottom: 0px;
}

</style>

<footer>
	<p>Posted by: Hege Refsnes</p>
	<p>Contact information: <a href="mailto:someone@example.com">someone@example.com</a>.</p>
</footer>

app/views/layouts/_header.html.erb
<header style="background-color:#BEF6A9; height:100px;">
	<div class="container">
        <div class="row">
          <div class="col-xs-3" style="margin-top:10px;">
			<% if signed_in? %>
				Logged in as <%= current_user.email %>.<br>
			    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
				| <%= link_to "Admin", admin_root_path %>
			<% else %>
				<%= link_to "Sign in", new_user_session_path %>
			<% end %>
		  </div>
		  <div class="col-xs-9">
		  	<div>
		  	</div>
		  </div>
		<div>
	<div>	 	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Blog</title>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <style type="text/css">
        html body{
            background-image: url('/assets/download.jpg');
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
        html,body {

        }
      </style>
     
    </head>

    <body>

 
      <%= render partial: 'layouts/header' %>

      <div id="wrap">
      <div id="main-container" class="container">
        <div class="row">
          <div class="col-xs-12">
            <% flash.each do |name, msg| -%>
              <%= content_tag :div, msg, class: "alert alert-#{name}" %>
            <% end -%>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3 sidebar">
            <h3>Tips for Articles</h3>
              <p>
                <ul>
                  <li>Get ideas from your audience</li>
                  <li>Understand your audience</li>
                  <li>Write for yourself first</li>
                  <li>Get ideas from your audience</li>
                  <li>Build your email list</li>
                  <li>Get ideas from your audience</li>
                  <li>Understand your audience</li>
                  <li>Get ideas from your audience</li>
                </ul>
              </p>
              <h3>Tips for Articles</h3>
              <p>
                <ul>
                  <li>Get ideas from your audience</li>
                  <li>Understand your audience</li>
                  <li>Write for yourself first</li>
                  <li>Get ideas from your audience</li>
                  <li>Build your email list</li>
                  <li>Get ideas from your audience</li>
                  <li>Understand your audience</li>
                  <li>Get ideas from your audience</li>
                </ul>
              </p>
          </div>
          <div class="col-xs-9">
            <%= yield %>
          </div>
        </div>
      </div>  

      <%= render partial: 'layouts/footer' %>
      <div>
 
    </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <header>
			<% if signed_in? %>
			    Logged in as <%= current_user.email %>.<br>
			    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
			    | <%= link_to "Admin", admin_root_path %>
			<% else %>
			    <%= link_to "Sign in", new_user_session_path %>
			<% end %>
	    </header>
    </div>
  </div>
</nav>